# frozen_string_literal: true

source 'https://rubygems.org'

gem 'minitest', group: 'development'
gem 'mutex_m', group: 'development'
gem 'rake', group: 'development'
gem 'rubocop', group: 'development', require: false
